# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pipejump}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Bunsch"]
  s.date = %q{2010-11-03}
  s.description = %q{Pipejump API Ruby client}
  s.email = %q{marcin@pipejump.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/pipejump.rb",
     "lib/pipejump/base/collection.rb",
     "lib/pipejump/base/connection.rb",
     "lib/pipejump/base/errors.rb",
     "lib/pipejump/base/resource.rb",
     "lib/pipejump/base/session.rb",
     "lib/pipejump/resources/account.rb",
     "lib/pipejump/resources/client.rb",
     "lib/pipejump/resources/contact.rb",
     "lib/pipejump/resources/deal.rb",
     "lib/pipejump/resources/note.rb",
     "lib/pipejump/resources/reminder.rb",
     "lib/pipejump/resources/source.rb",
     "spec/connection.sample.yml",
     "spec/pipejump/resources/client_spec.rb",
     "spec/pipejump/resources/contact_spec.rb",
     "spec/pipejump/resources/deal_spec.rb",
     "spec/pipejump/resources/note_spec.rb",
     "spec/pipejump/resources/reminder_spec.rb",
     "spec/pipejump/resources/source_spec.rb",
     "spec/pipejump/session_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/pipejump/pipejump}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pipejump API Ruby client}
  s.test_files = [
    "spec/pipejump/resources/client_spec.rb",
     "spec/pipejump/resources/contact_spec.rb",
     "spec/pipejump/resources/deal_spec.rb",
     "spec/pipejump/resources/note_spec.rb",
     "spec/pipejump/resources/reminder_spec.rb",
     "spec/pipejump/resources/source_spec.rb",
     "spec/pipejump/session_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
  end
end

